version: '3.9'

services:
  ams:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_FLYWAY_USER=${POSTGRES_USER}
      - SPRING_FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_FLYWAY_URL=${DB_URL}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres_container
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-account-management-db}
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U postgres", "-d password" ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: