spring:
  datasource:
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres15
    url: jdbc:postgresql://localhost:5432/account-management-db
  flyway:
    url: jdbc:postgresql://localhost:5432/account-management-db
    password: postgres
    user: postgres

springdoc:
    swagger-ui:
      path: /documentation/doc-ui.html
      url: /documentation/v3/api-docs
      disable-swagger-default-url: true
      configUrl: /documentation/v3/api-docs/swagger-config
      operationsSorter: alpha
      tagsSorter: alpha
    api-docs:
      path: /documentation/v3/api-docs

account-service:
  securityJWTKeyStorePath: config/keystore/keystore.jks
  securityJWTKeyStorePassword: ${JWT_PASSWORD:password}
  securityJWTKeyAlias: jwtsigning
  securityJWTPrivateKeyPassphrase: ${JWT_PRIVATE_KEY_PARAPHRASE:password}
  systemDefinedPermissions: config/permissions/systemPermissionUpdate.json
  loginAttemptMaxCount: 10
  loginAttemptAutoUnlockDuration: 30


