spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/account-management-db
  flyway:
    url: jdbc:postgresql://localhost:5432/account-management-db
    password: password
    user: postgres
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
  sql:
    init:
      platform: postgres
      mode: always
      continue-on-error: true
