BEGIN;
ALTER TABLE account DROP CONSTRAINT account_pkey;
ALTER TABLE account DROP COLUMN id;
ALTER TABLE account ADD COLUMN id BIGSERIAL PRIMARY KEY;
ALTER TABLE account ADD COLUMN customer_id BIGINT;
COMMIT